### ISSUE TITLE
Page: Homepage

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/energy-jti#10]
- [ ] Create about page using homepage layout

### Page Content

- [ ] Page Header (Issue #11):
     - [ ] Page title is Just Transition Initiative
     - [ ] Page description
     - [ ] Background Video
- [ ] Define JTI Section:
     - [ ] Title
     - [ ] Definition
     - [ ] Link to About JTI page (What is Just Transitions?)
     - [ ] Link Icon
- [ ] Filter Section:
     - [ ] Explore the Resource Library heading
     - [ ] Directions on filter use
     - [ ] Search Component
          - [ ] Placeholder Text
          - [ ] Search Icon
     - [ ] Geographic Focus 
          - [ ] Filter Functionality
          - [ ] Placeholder Text
     - [ ] Sectors
         - [ ] Filter Functionality
          - [ ] Placeholder Text
     - [ ] Focus Areas
          - [ ] Filter Functionality
          - [ ] Placeholder Text
     - [ ] Format
          - [ ] Filter Functionality
          - [ ] Placeholder Text
     - [ ] More filters can be found on the resource libraries page
          - [ ] text 
          - [ ] url to resources library page
     - [ ] Submit Button
- [ ] Analysis Section:
     - [ ] Heading
     - [ ] Byline
     - [ ] Featured Post-Block: 
          - [ ] Include Post-Block Component (Issue #9) with correct layout
          - [ ] Gray block background
     - [ ] Regular Analysis Posts:
          - [ ] Include Post-Block Component (Issue #9) with correct layout
          - [ ] All JTI Analysis Link
          - [ ] Arrow Icon
- [ ] Partnership Section:
     - [ ] JTI Icon
     - [ ] Define JTI Partnership
     - [ ] Learn more link
