### ISSUE TITLE
Component: Page Header

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/energy-jti#11]
- [x] Create Site Header for Various Pages

### Homepage Header
- [x] Background Video
- [x] Heading 
- [x] SubHeading
- [x] Mission Statement Block
- [x] Upcoming Event Block
- [x] Resource Library Filter

### Resource Library Header
<img width="746" alt="Screen Shot 2020-10-23 at 12 46 53 PM" src="https://user-images.githubusercontent.com/45780666/97031288-07e41880-152e-11eb-9093-87051488c910.png">

- [x] Background Image
- [x] Heading 
- [x] SubHeading
- [x] Description
- [x] Classifications
     - [x] Pop-up modal functionality
     - [x] List of terms 
     - [x] Info Icon
- [x] What is Just Transitions
     - [x] Text
     - [x] Link to About page
     - [x] Arrow Icon
- [x] Share
     - [x] Include Social Share Component (Issue #3) 

### Analysis Post Header
<img width="746" alt="Screen Shot 2020-10-23 at 1 10 57 PM" src="https://user-images.githubusercontent.com/45780666/97033374-3e6f6280-1531-11eb-961a-efb49b5a8a2c.png">

- [x] Background Image
- [x] Post Type
- [x] Post Title
- [x] Subtitle
- [x] Description
- [x] Publication Date
- [x] Photo of Analysis Post
- [x] Share
     - [x] Include Social Share Component (Issue #3) 

### Event Post Header
<img width="758" alt="Screen Shot 2020-10-23 at 1 18 03 PM" src="https://user-images.githubusercontent.com/45780666/97034008-3b28a680-1532-11eb-940e-62b21986220c.png">

- [x] Background Image
- [x] Post Type
- [x] Post Title
- [x] Subtitle
- [x] Description
- [x] Publication Date
- [x] Separating Element (border-right/after-element)
- [x] Event Date 
     - [x] Month
     - [x] Day
     - [x] Year
     - [x] Background Shading
- [x] Event Time 
- [x] Event Address
- [x] Share
     -[x] Include Social Share Component (Issue #3) 

### Past Event Header
<img width="758" alt="Screen Shot 2020-10-23 at 1 19 27 PM" src="https://user-images.githubusercontent.com/45780666/97034124-67442780-1532-11eb-9bda-73c4aff67e14.png">

- [x] Background Image
- [x] Post Type
- [x] Post Title
- [x] Subtitle
- [x] Description
- [x] Publication Date
- [x] Separating Element (border-right/after-element)
- [x] Calendar Icon
- [x] This event has already occurred text & styling
- [x] Include post-block component (Issue #9)
- [x] Share
     - [x] Include Social Share Component (Issue #3) 

### Archive Header/About JTI Header
<img width="758" alt="Screen Shot 2020-10-23 at 1 20 52 PM" src="https://user-images.githubusercontent.com/45780666/97034276-a70b0f00-1532-11eb-8f36-a779927792a9.png">

- [x] Background Image
- [x] Heading
- [x] Description
- [x] Share
     - [x] Include Social Share Component (Issue #3) 

### About Just Transitions Header
<img width="751" alt="Screen Shot 2020-10-23 at 1 22 14 PM" src="https://user-images.githubusercontent.com/45780666/97034386-d3bf2680-1532-11eb-9b62-d20cc8fa75af.png">

- [x] Background Image
- [x] Heading
- [x] Description
- [x] Photo
- [x] Share
     - [x] Include Social Share Component (Issue #3)
